inherit_gem:
  sanelint:
    - config/default.yml

Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
  - spec/**/*.rb

RSpec/NestedGroups:
  Max: 4

Style/MixinUsage:
  Exclude:
    - 'spec/factories/**/*'

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
  - 'config.ru'
  - 'Rakefile'
  - 'db/migrate/*'
  - 'db/schema.rb'
  - 'config/**/*'
  - 'bin/*'
  - 'vendor/**/*'
